"""File-system tools scoped to a research output directory.

Provides read, write, edit, bash, grep, find, and ls tools for an LLM agent
that synthesizes research outputs (glossaries, reports, summaries) from
markdown files generated by research_tree / research_expand.
"""

import os
import re
import shlex
import subprocess
from pathlib import Path


class ResearchTools:
    """File-system tools scoped to a research output directory.

    All paths are resolved relative to base_dir. Path traversal outside
    base_dir is blocked. Write operations are restricted to .md files.

    Usage:
        rt = ResearchTools("/path/to/research/output")
        agent = LLM(model=1)
        agent.tools(fns=rt.all_tools(), stop_tool=True, max_turns=20)
    """

    def __init__(self, base_dir: str):
        self.base_dir = os.path.realpath(os.path.expanduser(base_dir))
        if not os.path.isdir(self.base_dir):
            raise ValueError(f"base_dir does not exist: {self.base_dir}")

    def _resolve(self, path: str) -> str:
        """Resolve path relative to base_dir, block traversal outside it."""
        if os.path.isabs(path):
            resolved = os.path.realpath(path)
        else:
            resolved = os.path.realpath(os.path.join(self.base_dir, path))
        if resolved != self.base_dir and not resolved.startswith(self.base_dir + os.sep):
            raise ValueError(f"Path outside research directory: {path}")
        return resolved

    def _require_md(self, path: str) -> str | None:
        """Return error string if path doesn't end with .md, else None."""
        if not path.rstrip("/").endswith(".md"):
            return f"Error: Only .md files can be written. Got: {path}"
        return None

    # -- Tools --

    def read(self, path: str, offset: int = 0, limit: int = 2000) -> str:
        """Read file contents with line numbers.

        Args:
            path: File path relative to the research directory.
            offset: Line number to start reading from (0-based). Defaults to 0.
            limit: Maximum number of lines to return. Defaults to 2000, capped at 5000.

        Returns:
            File contents with line numbers, or error message.
        """
        try:
            resolved = self._resolve(path)
        except ValueError as e:
            return f"Error: {e}"
        if os.path.isdir(resolved):
            return f"Error: {path} is a directory, not a file. Use ls instead."
        try:
            with open(resolved, "r", encoding="utf-8", errors="replace") as f:
                all_lines = f.readlines()
        except FileNotFoundError:
            return f"Error: File not found: {path}"

        limit = min(limit, 5000)
        total = len(all_lines)
        selected = all_lines[offset:offset + limit]
        numbered = []
        for i, line in enumerate(selected):
            line_no = i + offset + 1
            numbered.append(f"{line_no:>6}\t{line}")
        result = "".join(numbered)
        if offset + limit < total:
            result += f"\n[... truncated, {total} total lines]"
        return result

    def write(self, path: str, content: str) -> str:
        """Write content to a markdown file. Creates parent directories as needed.

        Args:
            path: File path relative to the research directory. Must end with .md.
            content: The content to write to the file.

        Returns:
            Confirmation message with bytes written.
        """
        err = self._require_md(path)
        if err:
            return err
        try:
            resolved = self._resolve(path)
        except ValueError as e:
            return f"Error: {e}"
        os.makedirs(os.path.dirname(resolved) or ".", exist_ok=True)
        with open(resolved, "w", encoding="utf-8") as f:
            f.write(content)
        return f"Wrote {len(content.encode('utf-8'))} bytes to {path}"

    def edit(self, path: str, old_text: str, new_text: str) -> str:
        """Find and replace text in a markdown file.

        Args:
            path: File path relative to the research directory. Must be a .md file.
            old_text: The exact text to find. Must appear exactly once in the file.
            new_text: The replacement text.

        Returns:
            Confirmation with surrounding context, or error if not found or ambiguous.
        """
        err = self._require_md(path)
        if err:
            return err
        try:
            resolved = self._resolve(path)
        except ValueError as e:
            return f"Error: {e}"
        try:
            with open(resolved, "r", encoding="utf-8") as f:
                content = f.read()
        except FileNotFoundError:
            return f"Error: File not found: {path}"

        count = content.count(old_text)
        if count == 0:
            return f"Error: old_text not found in {path}"
        if count > 1:
            return f"Error: old_text found {count} times in {path}. Provide more context to make it unique."

        new_content = content.replace(old_text, new_text, 1)
        with open(resolved, "w", encoding="utf-8") as f:
            f.write(new_content)

        # Show context around the replacement
        lines = new_content.splitlines()
        new_lines = new_text.splitlines()
        # Find the first line of the replacement
        replace_start = None
        for i, line in enumerate(lines):
            if new_lines and new_lines[0] in line:
                replace_start = i
                break
        if replace_start is not None:
            ctx_start = max(0, replace_start - 3)
            ctx_end = min(len(lines), replace_start + len(new_lines) + 3)
            context = "\n".join(f"{i+1:>6}\t{lines[i]}" for i in range(ctx_start, ctx_end))
            return f"Replaced in {path}. Context:\n{context}"
        return f"Replaced in {path}."

    _BASH_ALLOWLIST = frozenset({
        "wc", "head", "tail", "sort", "uniq", "cat", "echo",
        "date", "diff", "tr", "cut", "paste", "comm", "expand",
    })

    _BASH_INJECTION_PATTERN = re.compile(r"\$\(|`|;|&&|\|\|")

    def bash(self, command: str) -> str:
        """Execute a restricted shell command in the research directory.

        Args:
            command: Shell command to execute. Only safe read-only commands are allowed:
                wc, head, tail, sort, uniq, cat, echo, date, diff, tr, cut, paste, comm, expand.
                Pipes between allowed commands are OK.

        Returns:
            Command output (stdout + stderr), truncated to 10000 characters.
        """
        # Block shell injection patterns
        if self._BASH_INJECTION_PATTERN.search(command):
            return "Error: Shell operators (;, &&, ||, $(), backticks) are not allowed."

        # Validate each pipe segment
        segments = command.split("|")
        for segment in segments:
            segment = segment.strip()
            if not segment:
                continue
            try:
                tokens = shlex.split(segment)
            except ValueError as e:
                return f"Error: Failed to parse command: {e}"
            if not tokens:
                continue
            base_cmd = os.path.basename(tokens[0])
            if base_cmd not in self._BASH_ALLOWLIST:
                allowed = ", ".join(sorted(self._BASH_ALLOWLIST))
                return f"Error: Command '{base_cmd}' is not allowed. Allowed: {allowed}"

        try:
            result = subprocess.run(
                command, shell=True, cwd=self.base_dir,
                capture_output=True, text=True, timeout=10,
            )
            output = result.stdout
            if result.stderr:
                output += result.stderr
        except subprocess.TimeoutExpired:
            return "Error: Command timed out after 10 seconds."

        if len(output) > 10000:
            output = output[:10000] + "\n[... truncated]"
        return output if output else "(no output)"

    def grep(self, pattern: str, path: str = ".", include: str = "*.md") -> str:
        """Search file contents using regex.

        Args:
            pattern: Regular expression pattern to search for.
            path: Directory or file to search in, relative to research directory. Defaults to current directory.
            include: Glob pattern to filter files. Defaults to *.md.

        Returns:
            Matching lines in file:line:content format, max 100 results.
        """
        try:
            resolved = self._resolve(path)
        except ValueError as e:
            return f"Error: {e}"
        try:
            compiled = re.compile(pattern)
        except re.error as e:
            return f"Error: Invalid regex pattern: {e}"

        matches = []
        search_path = Path(resolved)

        if search_path.is_file():
            files = [search_path]
        else:
            files = sorted(search_path.rglob(include))

        for fpath in files:
            if not fpath.is_file():
                continue
            try:
                with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                    for line_num, line in enumerate(f, 1):
                        if compiled.search(line):
                            rel = os.path.relpath(fpath, self.base_dir)
                            matches.append(f"{rel}:{line_num}:{line.rstrip()}")
                            if len(matches) >= 100:
                                break
            except (OSError, UnicodeDecodeError):
                continue
            if len(matches) >= 100:
                break

        if not matches:
            return "No matches found."
        result = "\n".join(matches)
        if len(matches) == 100:
            result += "\n[... capped at 100 results]"
        return result

    def find(self, pattern: str, path: str = ".") -> str:
        """Find files by glob pattern.

        Args:
            pattern: Glob pattern to match (e.g. *.md, *summary*).
            path: Directory to search in, relative to research directory. Defaults to current directory.

        Returns:
            Matching file paths relative to research directory, max 500 results.
        """
        try:
            resolved = self._resolve(path)
        except ValueError as e:
            return f"Error: {e}"

        search_path = Path(resolved)
        results = []
        for match in search_path.rglob(pattern):
            results.append(os.path.relpath(match, self.base_dir))
            if len(results) >= 500:
                break

        if not results:
            return "No files found."
        results.sort()
        output = "\n".join(results)
        if len(results) == 500:
            output += "\n[... capped at 500 results]"
        return output

    def ls(self, path: str = ".") -> str:
        """List directory contents with file sizes and types.

        Args:
            path: Directory path relative to the research directory. Defaults to current directory.

        Returns:
            Directory listing with type indicators (d=directory, f=file) and sizes.
        """
        try:
            resolved = self._resolve(path)
        except ValueError as e:
            return f"Error: {e}"
        if not os.path.isdir(resolved):
            return f"Error: {path} is not a directory."

        try:
            entries = sorted(os.listdir(resolved))
        except PermissionError:
            return f"Error: Permission denied: {path}"

        lines = []
        for name in entries[:200]:
            full = os.path.join(resolved, name)
            try:
                stat = os.stat(full)
                is_dir = os.path.isdir(full)
                kind = "d" if is_dir else "f"
                suffix = "/" if is_dir else ""
                lines.append(f"{kind} {stat.st_size:>8} {name}{suffix}")
            except OSError:
                lines.append(f"? {'?':>8} {name}")

        if not lines:
            return "(empty directory)"
        result = "\n".join(lines)
        if len(entries) > 200:
            result += f"\n[... capped at 200 of {len(entries)} entries]"
        return result

    # -- Groupings --

    def all_tools(self) -> list:
        """All research tools."""
        return [self.read, self.write, self.edit, self.bash, self.grep, self.find, self.ls]

    def read_tools(self) -> list:
        """Read-only tools (no file mutations)."""
        return [self.read, self.grep, self.find, self.ls]

    def write_tools(self) -> list:
        """Read + write tools (no bash)."""
        return [self.read, self.write, self.edit, self.grep, self.find, self.ls]
